### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by protpolymer** [protpolymer/credit-calculator#1]
Выходные данные должны быть такими же, как на сервисе банки.ру?

**Comment by coursar** [comment]
@protpolymer, у вас в презенташке в ДЗ отмечено, какие должны быть входные данные.

**Comment by protpolymer** [comment]
@coursar вопрос про выходные данные. Вы просто сказали, что для проверки использовать банки.ру или другой подходящий сервис. Но на разных сайтах выходные данные могут отличаться

**Comment by coursar** [comment]
@protpolymer, ок, моя ошибка - в качестве реализации выбираете рефенсный сервис, ответом должна быть общая сумма кредита.

**Comment by coursar** [comment]
@protpolymer, любой референсный, если banki.ru с вашей точки зрения считает некорректно.
